name: qanda-discord-bot

on: 
  push:
  pull_request: 
    branches: 
      - main

jobs:
  deploy:
    name: deploy in EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build and deploy
        env: 
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.HOSTNAME }}
          USER_NAME: ${{ secrets.USER_NAME }}

        # ssh into instance and deploy
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            cd /home/ubuntu/QandA-discord-bot &&
            git checkout main &&
            git fetch --all && 
            git reset --hard origin/main &&
            git pull origin main &&
            echo "DB_CONNECT=${{ secrets.DB_URI }}" > .env &&
            echo "TOKEN=${{ secrets.TOKEN }}" >> .env &&
            sudo docker build -t qanda-discord-bot . &&
            sudo docker run -d qanda-discord-bot 
            '
